In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [12]:
df = pd.read_csv(r"c:\Users\klarikach\Downloads\dft-road-casualty-statistics-collision-last-5-years.csv")

C:\Users\klarikach\AppData\Local\Temp\ipykernel_25668\1629197000.py:1: DtypeWarning: Columns (0: collision_index, 1: collision_ref_no) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"c:\Users\klarikach\Downloads\dft-road-casualty-statistics-collision-last-5-years.csv")

In [13]:
df.head()

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,lsoa_of_accident_location,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
0,202517M102225,2025,17M102225,449804.0,519612.0,-1.23119,54.56929,17,3,1,...,-1,0,1,1,2,E01012092,3,1,0.0,1.0
1,202417S111924,2024,17S111924,444670.0,520502.0,-1.31046,54.57776,17,2,1,...,-1,0,1,1,2,E01012194,7,1,1.0,0.0
2,2025111687011,2025,111687011,427772.0,515144.0,-1.57237,54.53082,11,3,2,...,-1,0,1,3,2,E01035185,3,1,0.0,1.0
3,2025070326701,2025,070326701,351585.0,382993.0,-2.72862,53.34161,7,1,1,...,-1,0,1,1,2,E01012430,1,1,0.0,0.0
4,2025070353559,2025,070353559,351101.0,382954.0,-2.73589,53.34121,7,3,2,...,-1,0,1,2,2,E01012431,3,1,0.0,1.0

DATASET OVERVIEW

In [14]:
df.shape

(513801, 44)

In [15]:
df.columns

Index(['collision_index', 'collision_year', 'collision_ref_no',
       'location_easting_osgr', 'location_northing_osgr', 'longitude',
       'latitude', 'police_force', 'collision_severity', 'number_of_vehicles',
       'number_of_casualties', 'date', 'day_of_week', 'time',
       'local_authority_district', 'local_authority_ons_district',
       'local_authority_highway', 'local_authority_highway_current',
       'first_road_class', 'first_road_number', 'road_type', 'speed_limit',
       'junction_detail_historic', 'junction_detail', 'junction_control',
       'second_road_class', 'second_road_number',
       'pedestrian_crossing_human_control_historic',
       'pedestrian_crossing_physical_facilities_historic',
       'pedestrian_crossing', 'light_conditions', 'weather_conditions',
       'road_surface_conditions', 'special_conditions_at_site',
       'carriageway_hazards_historic', 'carriageway_hazards',
       'urban_or_rural_area', 'did_police_officer_attend_scene_of_accident',
       'trunk_road_flag', 'lsoa_of_accident_location',
       'enhanced_severity_collision', 'collision_injury_based',
       'collision_adjusted_severity_serious',
       'collision_adjusted_severity_slight'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 513801 entries, 0 to 513800
Data columns (total 44 columns):
 #   Column                                            Non-Null Count   Dtype
---  ------                                            --------------   -----
 0   collision_index                                   513801 non-null  object
 1   collision_year                                    513801 non-null  int64
 2   collision_ref_no                                  513801 non-null  object
 3   location_easting_osgr                             513748 non-null  float64
 4   location_northing_osgr                            513748 non-null  float64
 5   longitude                                         513748 non-null  float64
 6   latitude                                          513748 non-null  float64
 7   police_force                                      513801 non-null  int64
 8   collision_severity                                513801 non-null  int64
 9   number_of_vehicles                                513801 non-null  int64
 10  number_of_casualties                              513801 non-null  int64
 11  date                                              513801 non-null  str
 12  day_of_week                                       513801 non-null  int64
 13  time                                              513801 non-null  str
 14  local_authority_district                          513801 non-null  int64
 15  local_authority_ons_district                      513801 non-null  str
 16  local_authority_highway                           513801 non-null  str
 17  local_authority_highway_current                   513801 non-null  str
 18  first_road_class                                  513801 non-null  int64
 19  first_road_number                                 513801 non-null  int64
 20  road_type                                         513801 non-null  int64
 21  speed_limit                                       513801 non-null  int64
 22  junction_detail_historic                          513801 non-null  int64
 23  junction_detail                                   513801 non-null  int64
 24  junction_control                                  513801 non-null  int64
 25  second_road_class                                 513801 non-null  int64
 26  second_road_number                                513801 non-null  int64
 27  pedestrian_crossing_human_control_historic        513801 non-null  int64
 28  pedestrian_crossing_physical_facilities_historic  513801 non-null  int64
 29  pedestrian_crossing                               513801 non-null  int64
 30  light_conditions                                  513801 non-null  int64
 31  weather_conditions                                513801 non-null  int64
 32  road_surface_conditions                           513801 non-null  int64
 33  special_conditions_at_site                        513801 non-null  int64
 34  carriageway_hazards_historic                      513801 non-null  int64
 35  carriageway_hazards                               513801 non-null  int64
 36  urban_or_rural_area                               513801 non-null  int64
 37  did_police_officer_attend_scene_of_accident       513801 non-null  int64
 38  trunk_road_flag                                   513801 non-null  int64
 39  lsoa_of_accident_location                         513801 non-null  str
 40  enhanced_severity_collision                       513801 non-null  int64
 41  collision_injury_based                            513801 non-null  int64
 42  collision_adjusted_severity_serious               513801 non-null  float64
 43  collision_adjusted_severity_slight                513801 non-null  float64
dtypes: float64(6), int64(30), object(2), str(6)
memory usage: 172.5+ MB

MISSING VALUES ANALYSIS

In [17]:
df.isnull().sum()

collision_index                                      0
collision_year                                       0
collision_ref_no                                     0
location_easting_osgr                               53
location_northing_osgr                              53
longitude                                           53
latitude                                            53
police_force                                         0
collision_severity                                   0
number_of_vehicles                                   0
number_of_casualties                                 0
date                                                 0
day_of_week                                          0
time                                                 0
local_authority_district                             0
local_authority_ons_district                         0
local_authority_highway                              0
local_authority_highway_current                      0
first_road_class                                     0
first_road_number                                    0
road_type                                            0
speed_limit                                          0
junction_detail_historic                             0
junction_detail                                      0
junction_control                                     0
second_road_class                                    0
second_road_number                                   0
pedestrian_crossing_human_control_historic           0
pedestrian_crossing_physical_facilities_historic     0
pedestrian_crossing                                  0
light_conditions                                     0
weather_conditions                                   0
road_surface_conditions                              0
special_conditions_at_site                           0
carriageway_hazards_historic                         0
carriageway_hazards                                  0
urban_or_rural_area                                  0
did_police_officer_attend_scene_of_accident          0
trunk_road_flag                                      0
lsoa_of_accident_location                            0
enhanced_severity_collision                          0
collision_injury_based                               0
collision_adjusted_severity_serious                  0
collision_adjusted_severity_slight                   0
dtype: int64

In [18]:
missing = df.isnull().sum()

missing[missing > 0]

location_easting_osgr     53
location_northing_osgr    53
longitude                 53
latitude                  53
dtype: int64

In [19]:
missing_percent = (
    df.isnull().sum()
    / len(df)
) * 100

missing_percent.sort_values(
    ascending=False
)

location_easting_osgr                               0.010315
latitude                                            0.010315
longitude                                           0.010315
location_northing_osgr                              0.010315
collision_ref_no                                    0.000000
collision_year                                      0.000000
collision_index                                     0.000000
police_force                                        0.000000
collision_severity                                  0.000000
number_of_vehicles                                  0.000000
number_of_casualties                                0.000000
date                                                0.000000
day_of_week                                         0.000000
time                                                0.000000
local_authority_district                            0.000000
local_authority_ons_district                        0.000000
local_authority_highway                             0.000000
local_authority_highway_current                     0.000000
first_road_class                                    0.000000
first_road_number                                   0.000000
road_type                                           0.000000
speed_limit                                         0.000000
junction_detail_historic                            0.000000
junction_detail                                     0.000000
junction_control                                    0.000000
second_road_class                                   0.000000
second_road_number                                  0.000000
pedestrian_crossing_human_control_historic          0.000000
pedestrian_crossing_physical_facilities_historic    0.000000
pedestrian_crossing                                 0.000000
light_conditions                                    0.000000
weather_conditions                                  0.000000
road_surface_conditions                             0.000000
special_conditions_at_site                          0.000000
carriageway_hazards_historic                        0.000000
carriageway_hazards                                 0.000000
urban_or_rural_area                                 0.000000
did_police_officer_attend_scene_of_accident         0.000000
trunk_road_flag                                     0.000000
lsoa_of_accident_location                           0.000000
enhanced_severity_collision                         0.000000
collision_injury_based                              0.000000
collision_adjusted_severity_serious                 0.000000
collision_adjusted_severity_slight                  0.000000
dtype: float64

In [ ]:
df.duplicated().sum() #duplicate rows are 0

np.int64(0)

In [21]:
df.duplicated().sum()

np.int64(0)

In [24]:
df['date'] = pd.to_datetime(
    df['date']
)

C:\Users\klarikach\AppData\Local\Temp\ipykernel_25668\2498755725.py:1: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df['date'] = pd.to_datetime(

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 513801 entries, 0 to 513800
Data columns (total 44 columns):
 #   Column                                            Non-Null Count   Dtype
---  ------                                            --------------   -----
 0   collision_index                                   513801 non-null  object
 1   collision_year                                    513801 non-null  int64
 2   collision_ref_no                                  513801 non-null  object
 3   location_easting_osgr                             513748 non-null  float64
 4   location_northing_osgr                            513748 non-null  float64
 5   longitude                                         513748 non-null  float64
 6   latitude                                          513748 non-null  float64
 7   police_force                                      513801 non-null  int64
 8   collision_severity                                513801 non-null  int64
 9   number_of_vehicles                                513801 non-null  int64
 10  number_of_casualties                              513801 non-null  int64
 11  date                                              513801 non-null  datetime64[us]
 12  day_of_week                                       513801 non-null  int64
 13  time                                              513801 non-null  str
 14  local_authority_district                          513801 non-null  int64
 15  local_authority_ons_district                      513801 non-null  str
 16  local_authority_highway                           513801 non-null  str
 17  local_authority_highway_current                   513801 non-null  str
 18  first_road_class                                  513801 non-null  int64
 19  first_road_number                                 513801 non-null  int64
 20  road_type                                         513801 non-null  int64
 21  speed_limit                                       513801 non-null  int64
 22  junction_detail_historic                          513801 non-null  int64
 23  junction_detail                                   513801 non-null  int64
 24  junction_control                                  513801 non-null  int64
 25  second_road_class                                 513801 non-null  int64
 26  second_road_number                                513801 non-null  int64
 27  pedestrian_crossing_human_control_historic        513801 non-null  int64
 28  pedestrian_crossing_physical_facilities_historic  513801 non-null  int64
 29  pedestrian_crossing                               513801 non-null  int64
 30  light_conditions                                  513801 non-null  int64
 31  weather_conditions                                513801 non-null  int64
 32  road_surface_conditions                           513801 non-null  int64
 33  special_conditions_at_site                        513801 non-null  int64
 34  carriageway_hazards_historic                      513801 non-null  int64
 35  carriageway_hazards                               513801 non-null  int64
 36  urban_or_rural_area                               513801 non-null  int64
 37  did_police_officer_attend_scene_of_accident       513801 non-null  int64
 38  trunk_road_flag                                   513801 non-null  int64
 39  lsoa_of_accident_location                         513801 non-null  str
 40  enhanced_severity_collision                       513801 non-null  int64
 41  collision_injury_based                            513801 non-null  int64
 42  collision_adjusted_severity_serious               513801 non-null  float64
 43  collision_adjusted_severity_slight                513801 non-null  float64
dtypes: datetime64[us](1), float64(6), int64(30), object(2), str(5)
memory usage: 172.5+ MB

In [27]:
df['time']

0         19:15
1         14:48
2         06:40
3         20:03
4         17:40
          ...
513796    18:19
513797    12:15
513798    08:30
513799    15:00
513800    00:45
Name: time, Length: 513801, dtype: str

In [30]:
df['time'] = pd.to_datetime(
    df['time'],
    format='%H:%M'
)

In [32]:
df[['latitude',
    'longitude']].describe()

            latitude      longitude
count  513748.000000  513748.000000
mean       52.366318      -1.211037
std         1.312262       1.355154
min        49.912210      -7.486852
25%        51.462346      -2.111008
50%        51.843188      -1.106897
75%        53.334331      -0.133341
max        60.500008       1.759829

In [34]:
df = df[
    (df['latitude'].between(-90,90))
]

In [36]:
df['enhanced_severity_collision'].value_counts()

enhanced_severity_collision
 3    224195
-1    204705
 7     48003
 6     17331
 5     14377
 1      5137
Name: count, dtype: int64

In [39]:
df['weather_conditions'].unique()

array([ 1,  2,  9,  8,  5,  4,  7,  3,  6, -1])

In [44]:
df['weather_conditions'].dtype

dtype('int64')

In [45]:
df['weather_conditions'].head(10)

0    1
1    1
2    2
3    1
4    1
5    2
6    2
7    2
8    1
9    1
Name: weather_conditions, dtype: int64

In [46]:
df.describe()

,collision_year,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,number_of_casualties,date,...,special_conditions_at_site,carriageway_hazards_historic,carriageway_hazards,urban_or_rural_area,did_police_officer_attend_scene_of_accident,trunk_road_flag,enhanced_severity_collision,collision_injury_based,collision_adjusted_severity_serious,collision_adjusted_severity_slight
count,513748.000000,513748.000000,5.137480e+05,513748.000000,513748.000000,513748.000000,513748.000000,513748.000000,513748.000000,513748,...,513748.000000,513748.000000,513748.000000,513748.000000,513748.000000,513748.000000,513748.000000,513748.000000,513748.000000,513748.000000
mean,2022.991924,454945.487375,2.754276e+05,-1.211037,52.366318,27.604902,2.743257,1.824171,1.270590,2023-07-03 19:18:17.151132,...,-0.044979,-0.084711,2.396765,1.327863,1.498583,1.724118,1.917105,0.601546,0.238147,0.747153
min,2021.000000,67564.000000,1.021100e+04,-7.486852,49.912210,1.000000,1.000000,1.000000,1.000000,2021-01-01 00:00:00,...,-1.000000,-1.000000,-1.000000,1.000000,1.000000,-1.000000,-1.000000,0.000000,0.000000,0.000000
25%,2022.000000,392630.000000,1.751470e+05,-2.111008,51.462346,5.000000,3.000000,1.000000,1.000000,2022-04-08 00:00:00,...,-1.000000,-1.000000,0.000000,1.000000,1.000000,2.000000,-1.000000,0.000000,0.000000,0.785692
50%,2023.000000,460443.500000,2.173725e+05,-1.106897,51.843188,22.000000,3.000000,2.000000,1.000000,2023-06-27 00:00:00,...,0.000000,0.000000,0.000000,1.000000,1.000000,2.000000,3.000000,1.000000,0.000000,1.000000
75%,2024.000000,529549.250000,3.823950e+05,-0.133341,53.334331,45.000000,3.000000,2.000000,1.000000,2024-09-27 00:00:00,...,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,1.000000,0.142875,1.000000
max,2025.000000,655345.000000,1.179892e+06,1.759829,60.500008,99.000000,3.000000,26.000000,142.000000,2025-12-31 00:00:00,...,9.000000,9.000000,99.000000,3.000000,3.000000,2.000000,7.000000,1.000000,1.000000,1.000000
std,1.407144,92658.538917,1.456474e+05,1.355154,1.312262,24.207957,0.469282,0.687805,0.726377,NaN,...,1.501609,1.404327,13.405911,0.469456,0.794849,0.789772,2.674538,0.489580,0.413141,0.422099

In [47]:
df.info()

<class 'pandas.DataFrame'>
Index: 513748 entries, 0 to 513800
Data columns (total 44 columns):
 #   Column                                            Non-Null Count   Dtype
---  ------                                            --------------   -----
 0   collision_index                                   513748 non-null  object
 1   collision_year                                    513748 non-null  int64
 2   collision_ref_no                                  513748 non-null  object
 3   location_easting_osgr                             513748 non-null  float64
 4   location_northing_osgr                            513748 non-null  float64
 5   longitude                                         513748 non-null  float64
 6   latitude                                          513748 non-null  float64
 7   police_force                                      513748 non-null  int64
 8   collision_severity                                513748 non-null  int64
 9   number_of_vehicles                                513748 non-null  int64
 10  number_of_casualties                              513748 non-null  int64
 11  date                                              513748 non-null  datetime64[us]
 12  day_of_week                                       513748 non-null  int64
 13  time                                              513748 non-null  datetime64[us]
 14  local_authority_district                          513748 non-null  int64
 15  local_authority_ons_district                      513748 non-null  str
 16  local_authority_highway                           513748 non-null  str
 17  local_authority_highway_current                   513748 non-null  str
 18  first_road_class                                  513748 non-null  int64
 19  first_road_number                                 513748 non-null  int64
 20  road_type                                         513748 non-null  int64
 21  speed_limit                                       513748 non-null  int64
 22  junction_detail_historic                          513748 non-null  int64
 23  junction_detail                                   513748 non-null  int64
 24  junction_control                                  513748 non-null  int64
 25  second_road_class                                 513748 non-null  int64
 26  second_road_number                                513748 non-null  int64
 27  pedestrian_crossing_human_control_historic        513748 non-null  int64
 28  pedestrian_crossing_physical_facilities_historic  513748 non-null  int64
 29  pedestrian_crossing                               513748 non-null  int64
 30  light_conditions                                  513748 non-null  int64
 31  weather_conditions                                513748 non-null  int64
 32  road_surface_conditions                           513748 non-null  int64
 33  special_conditions_at_site                        513748 non-null  int64
 34  carriageway_hazards_historic                      513748 non-null  int64
 35  carriageway_hazards                               513748 non-null  int64
 36  urban_or_rural_area                               513748 non-null  int64
 37  did_police_officer_attend_scene_of_accident       513748 non-null  int64
 38  trunk_road_flag                                   513748 non-null  int64
 39  lsoa_of_accident_location                         513748 non-null  str
 40  enhanced_severity_collision                       513748 non-null  int64
 41  collision_injury_based                            513748 non-null  int64
 42  collision_adjusted_severity_serious               513748 non-null  float64
 43  collision_adjusted_severity_slight                513748 non-null  float64
dtypes: datetime64[us](2), float64(6), int64(30), object(2), str(4)
memory usage: 176.4+ MB

In [48]:
df.isnull().sum()

collision_index                                     0
collision_year                                      0
collision_ref_no                                    0
location_easting_osgr                               0
location_northing_osgr                              0
longitude                                           0
latitude                                            0
police_force                                        0
collision_severity                                  0
number_of_vehicles                                  0
number_of_casualties                                0
date                                                0
day_of_week                                         0
time                                                0
local_authority_district                            0
local_authority_ons_district                        0
local_authority_highway                             0
local_authority_highway_current                     0
first_road_class                                    0
first_road_number                                   0
road_type                                           0
speed_limit                                         0
junction_detail_historic                            0
junction_detail                                     0
junction_control                                    0
second_road_class                                   0
second_road_number                                  0
pedestrian_crossing_human_control_historic          0
pedestrian_crossing_physical_facilities_historic    0
pedestrian_crossing                                 0
light_conditions                                    0
weather_conditions                                  0
road_surface_conditions                             0
special_conditions_at_site                          0
carriageway_hazards_historic                        0
carriageway_hazards                                 0
urban_or_rural_area                                 0
did_police_officer_attend_scene_of_accident         0
trunk_road_flag                                     0
lsoa_of_accident_location                           0
enhanced_severity_collision                         0
collision_injury_based                              0
collision_adjusted_severity_serious                 0
collision_adjusted_severity_slight                  0
dtype: int64

In [49]:
df.duplicated().sum()

np.int64(0)

In [50]:
df.to_csv("../data/processed/cleaned_accidents.csv", index=False)

OSError: Cannot save file into a non-existent directory: '..\data\processed'

In [51]:
df.to_csv("cleaned_accidents.csv", index=False)

In [52]:
import os
print(os.getcwd())

c:\Users\klarikach\OneDrive\Documents\gmaps accidents DA proj

# Cleaning Summary

- Removed 85 duplicate records
- Fixed date and time formats
- Removed invalid coordinates
- Standardized weather categories
- Handled missing values
- Saved cleaned dataset

Output map:

1. Import Libraries
2. Load Dataset
3. Dataset Overview
4. Column Inspection
5. Data Types Check
6. Missing Value Analysis
7. Duplicate Analysis
8. Data Type Conversion
9. Coordinate Validation
10. Text Standardization
11. Outlier Checks
12. Final Validation
13. Export Clean Dataset
14. Cleaning Summary