In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("cleaned_accidents.csv")

C:\Users\klarikach\AppData\Local\Temp\ipykernel_9008\1761719677.py:1: DtypeWarning: Columns (0: collision_index, 1: collision_ref_no) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("cleaned_accidents.csv")

In [3]:
df.columns.tolist()

['collision_index',
 'collision_year',
 'collision_ref_no',
 'location_easting_osgr',
 'location_northing_osgr',
 'longitude',
 'latitude',
 'police_force',
 'collision_severity',
 'number_of_vehicles',
 'number_of_casualties',
 'date',
 'day_of_week',
 'time',
 'local_authority_district',
 'local_authority_ons_district',
 'local_authority_highway',
 'local_authority_highway_current',
 'first_road_class',
 'first_road_number',
 'road_type',
 'speed_limit',
 'junction_detail_historic',
 'junction_detail',
 'junction_control',
 'second_road_class',
 'second_road_number',
 'pedestrian_crossing_human_control_historic',
 'pedestrian_crossing_physical_facilities_historic',
 'pedestrian_crossing',
 'light_conditions',
 'weather_conditions',
 'road_surface_conditions',
 'special_conditions_at_site',
 'carriageway_hazards_historic',
 'carriageway_hazards',
 'urban_or_rural_area',
 'did_police_officer_attend_scene_of_accident',
 'trunk_road_flag',
 'lsoa_of_accident_location',
 'enhanced_severity_collision',
 'collision_injury_based',
 'collision_adjusted_severity_serious',
 'collision_adjusted_severity_slight']

In [4]:
df['date'] = pd.to_datetime(df['date'])

In [5]:
df['year'] = df['date'].dt.year

In [6]:
df['month'] = df['date'].dt.month

In [7]:
df['month_name'] = df['date'].dt.month_name()

In [8]:
df['day'] = df['date'].dt.day

In [9]:
df['weekday'] = df['date'].dt.day_name()

In [10]:
df['quarter'] = df['date'].dt.quarter

In [12]:
df['time'].head()

0    1900-01-01 19:15:00
1    1900-01-01 14:48:00
2    1900-01-01 06:40:00
3    1900-01-01 20:03:00
4    1900-01-01 17:40:00
Name: time, dtype: str

In [13]:
df['time'].dtype

In [14]:
df['time'] = pd.to_datetime(df['time'])

In [15]:
df['hour'] = df['time'].dt.hour

In [16]:
df[['time', 'hour']].head()

                 time  hour
0 1900-01-01 19:15:00    19
1 1900-01-01 14:48:00    14
2 1900-01-01 06:40:00     6
3 1900-01-01 20:03:00    20
4 1900-01-01 17:40:00    17

In [17]:
def time_bucket(hour):
    if 5 <= hour < 12:
        return "Morning"
    elif 12 <= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

df['time_bucket'] = df['hour'].apply(time_bucket)

In [18]:
df[['hour', 'time_bucket']].head()

   hour time_bucket
0    19     Evening
1    14   Afternoon
2     6     Morning
3    20     Evening
4    17     Evening

In [19]:
df['is_weekend'] = df['weekday'].isin(
    ['Saturday', 'Sunday']
)

In [20]:
df.head()

,collision_index,collision_year,collision_ref_no,location_easting_osgr,location_northing_osgr,longitude,latitude,police_force,collision_severity,number_of_vehicles,...,collision_adjusted_severity_slight,year,month,month_name,day,weekday,quarter,hour,time_bucket,is_weekend
0,202517M102225,2025,17M102225,449804.0,519612.0,-1.23119,54.56929,17,3,1,...,1.0,2025,2,February,15,Saturday,1,19,Evening,True
1,202417S111924,2024,17S111924,444670.0,520502.0,-1.31046,54.57776,17,2,1,...,0.0,2024,10,October,22,Tuesday,4,14,Afternoon,False
2,2025111687011,2025,111687011,427772.0,515144.0,-1.57237,54.53082,11,3,2,...,1.0,2025,12,December,19,Friday,4,6,Morning,False
3,2025070326701,2025,070326701,351585.0,382993.0,-2.72862,53.34161,7,1,1,...,0.0,2025,4,April,22,Tuesday,2,20,Evening,False
4,2025070353559,2025,070353559,351101.0,382954.0,-2.73589,53.34121,7,3,2,...,1.0,2025,4,April,28,Monday,2,17,Evening,False

In [21]:
df.to_csv(
    "feature_engineered_accidents.csv",
    index=False
)